#+TITLE: chlsdl-modules
#+AUTHOR: usadev1984
#+LANGUAGE: en

modules repo for [[https://github.com/usadev1984/chlsdl][chlsdl]] which hosts modules for all of the supported sources.
** supported sources
- danbooru (images, gifs, videos)
- r34 (images, gifs, videos)
- gelbooru (images, gifs, videos)
** dependencies
the full dependencies (some module may not depend on all of these) are:
- pcre2
- json-c
- curl
- libnotify (optional. push notifications)
- pkg-config (build-time only)
- openssl (file integrity checking)
** building
*** options
- ~COLOR~: if you want colored output and your terminal has truecolor support, pass ~COLOR=1~ to ~make~ (recommended).
- ~PREFIX~: controls the directory where everything is going to be installed. you most likely don't need to set this variable.
*** building
- build modules:
#+BEGIN_SRC shell
make -j$((`nproc`+1)) modules COLOR=1
#+END_SRC
- install with:
#+BEGIN_SRC shell
  sudo make install
#+END_SRC
- finally, add the javascript userscript for each module you intend to use in [[https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/][violent monkey]] from [[https://github.com/usadev1984/chlsdl-modules/tree/master/js-scripts][js-scripts]].
*NOTES*:
- to build only two modules where ~$mod_1~ and ~$mod_2~ are the names of the module directories, pass ~MODULES="lib${mod_1} lib${mod_2}"~ to both commands. example:
#+BEGIN_SRC shell
make -j$((`nproc`+1)) modules MODULES="lib${mod_1} lib${mod_2}" COLOR=1
sudo make install MODULES="lib${mod_1} lib${mod_2}"
#+END_SRC
- if you alter the value of ~$PREFIX~, you *MUST* use the same value when building the main program
** todo
- [ ] fix building on nixos
- [ ] fix build system
  - [ ] figure out a good project structure
- [X] support videos and gifs from danbooru
- [X] add support for r34
